MAIN_URL = 'https://livetv775.me'

CATEGORIES = {
    'american_football': 27,
    'athletics': 9,
    'bandy': 11,
    'baseball': 19,
    'basketball': 3,
    'beach_soccer': 23,
    'billiard': 29,
    'combat_sport': 75,
    'cricket': 41,
    'cycling': 40,
    'darts': 30,
    'field_hockey': 38,
    'floorball': 32,
    'football': 1,
    'futsal': 12,
    'golf': 37,
    'handball': 13,
    'ice_hockey': 2,
    'mma': 110,
    'netball': 96,
    'padel_tennis': 71,
    'racing': 7,
    'rugby_league': 17,
    'rugby_sevens': 77,
    'rugby_union': 33,
    'table_tennis': 39,
    'tennis': 4,
    'volleyball': 5,
    'winter_sport': 18
}
