EVENTS_URL = 'https://livetv.sx'
ALTERNATIVE_EVENTS_URL = 'https://livetv855.me'
CHANNELS_URL = 'https://ipfs.io/ipns/elcano.top'

CATEGORIES = {
    'american_football': 27,
    'athletics': 9,
    'aussie_rules': 52,
    'badminton': 31,
    'bandy': 11,
    'baseball': 19,
    'basketball': 3,
    'beach_soccer': 23,
    'beach_volleyball': 21,
    'billiard': 29,
    'boxing': 6,
    'climbing': 93,
    'combat_sport': 75,
    'cricket': 41,
    'cycling': 40,
    'darts': 30,
    'e_sports': 74,
    'field_hockey': 38,
    'floorball': 32,
    'football': 1,
    'futsal': 12,
    'golf': 37,
    'handball': 13,
    'ice_hockey': 2,
    'lacrosse': 42,
    'mma': 110,
    'netball': 96,
    'padel_tennis': 71,
    'racing': 7,
    'rugby_league': 17,
    'rugby_sevens': 77,
    'rugby_union': 33,
    'table_tennis': 39,
    'tennis': 4,
    'triathlon': 76,
    'volleyball': 5,
    'water_polo': 22,
    'water_sports': 46,
    'winter_sport': 18
}
