name: build-tag-release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: Release Type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      tag_and_release:
        description: Create tag and release
        required: true
        type: boolean
        default: false

jobs:
  build-binaries:
    strategy:
      matrix:
        flavour:
          - runner: ubuntu-latest
            os: linux
          - runner: windows-latest
            os: windows
    runs-on: ${{ matrix.flavour.runner }}
    steps:
      - name: Package ${{ runner.os }} application
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: acestream_search.spec
          requirements: requirements.txt
          upload_exe_with_name: binaries-${{ matrix.flavour.os }}
  tag-and-release:
    if: ${{ inputs.tag_and_release == true }}
    needs: build-binaries
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ inputs.bump_type}}
      - uses: actions/download-artifact@v4
      - run: >-
          cd binaries-linux &&
          chmod +x acestream-search &&
          chmod +x acestream-search-gui &&
          tar czvf acestream-search-linux-binary-${{ steps.tag_version.outputs.new_tag }}.tar.gz acestream-search &&
          tar czvf acestream-search-gui-linux-binary-${{ steps.tag_version.outputs.new_tag }}.tar.gz acestream-search-gui
      - run: >-
          cd binaries-windows &&
          zip acestream-search-windows-binary-${{ steps.tag_version.outputs.new_tag }}.zip acestream-search.exe &&
          zip acestream-search-gui-windows-binary-${{ steps.tag_version.outputs.new_tag }}.zip acestream-search-gui.exe
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: >-
            binaries-linux/acestream-search-linux-binary-${{ steps.tag_version.outputs.new_tag }}.tar.gz,
            binaries-windows/acestream-search-windows-binary-${{ steps.tag_version.outputs.new_tag }}.zip,
            binaries-linux/acestream-search-gui-linux-binary-${{ steps.tag_version.outputs.new_tag }}.tar.gz,
            binaries-windows/acestream-search-gui-windows-binary-${{ steps.tag_version.outputs.new_tag }}.zip
          artifactErrorsFailBuild: true
