name: test-python-install

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  python-install:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install application
      run: pip install .
    - name: Test that console application runs (${{ runner.os }})
      run: acestream-search --help
